name: Python Tests

on:
  push:
    branches: [main, Benchmark]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04  # Use stable runner with broader Python support

    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.13]

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt || true  # Optional: skip if missing

    - name: Run tests with pytest
      run: |
        pytest src/benchmark/tests/
