name: Python Tests

on:
  push:
    branches: [main, Benchmark]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.13]  # Add more versions as needed

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt || true  # Optional dev reqs like pytest

    - name: Run tests with pytest
      run: |
        pytest src/benchmark/tests/
